# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

RUN pip install --upgrade pip

COPY requirements_server.txt .
RUN pip install --no-cache-dir -r requirements_server.txt

COPY server.py .
COPY . .

EXPOSE 4320


CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "4320"]

